name: Docker Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify the tag to build and release'
        required: true
      name:
        description: 'Specify the name of this release'
        required: true
      body:
        description: 'Describe for this release'
        required: false

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Set tag name
      id: set_tag
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "Using tag from manual inputs"
          echo "TAG_NAME=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
        else
          echo "Using tag from push event"
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi

    - name: Set release name
      id: set_release_name
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "Using release name from manual inputs"
          echo "RELEASE_NAME=${{ github.event.inputs.name }}" >> $GITHUB_OUTPUT
        else
          echo "Using tag from push event"
          echo "RELEASE_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi

    - name: Set body
      id: set_body
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "Using tag from manual inputs"
          echo "BODY=${{ github.event.inputs.body }}" >> $GITHUB_OUTPUT
        else
          echo "Using tag from push event"
          echo "BODY=" >> $GITHUB_OUTPUT
        fi

    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.set_tag.outputs.TAG_NAME }}

    - name: Build with Docker
      run: |
        mkdir output
        docker compose -f ./.devcontainer/docker-compose.yml build
        docker compose -f ./.devcontainer/docker-compose.yml up -d
        docker exec $(docker ps -q --filter name=latex) sh -c "cd /home/src && lualatex test"
        docker cp $(docker ps -q --filter name=latex):/home/src/test.pdf ./output/test.pdf
    
    - name: Upload release asset
      uses: softprops/action-gh-release@v2.0.2
      with:
        files: |
          ./output/test.pdf
        tag_name:
          ${{ steps.set_tag.outputs.TAG_NAME }}
        name:
          ${{ steps.set_release_name.outputs.RELEASE_NAME }}
        body:
          ${{ steps.set_body.outputs.BODY }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
