name: Docker Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify the tag to build and release'
        required: true
      name:
        description: 'Specify the name of this release'
        required: true
      body:
        description: 'Describe for this release'
        required: false

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ steps.set_tag.outputs.TAG_NAME }}
    
    - name: Set tag name
      id: set_tag
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "Manually"
          echo "TAG_NAME=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
        else
          echo "On push"
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi

    - name: Set release name
      id: set_release_name
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "Manually"
          echo "RELEASE_NAME=${{ github.event.inputs.name }}" >> $GITHUB_OUTPUT
        else
          echo "On push"
          echo "RELEASE_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        fi

    - name: Get tag comment
      id: get_tag_comment
      uses: actions/github-script@v7
      with:
        script: |
          const tagRef = context.ref;
          const [owner, repo] = context.repo();
          const tagInfo = await github.git.getTag({
            owner: owner,
            repo: repo,
            tag_sha: tagRef
          });
          const message = tagInfo.data.message
          console.log(message);
          return message;
        result-encoding: string
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set body
      id: set_body
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          echo "Manually"
          echo "BODY=${{ github.event.inputs.body }}" >> $GITHUB_OUTPUT
        else
          echo "On push"
          echo "BODY=${{ steps.get_tag_comment.outputs.result }}" >> $GITHUB_OUTPUT
        fi

    - name: Build with Docker
      run: |
        mkdir output
        docker compose -f ./.devcontainer/docker-compose.yml build
        docker compose -f ./.devcontainer/docker-compose.yml up -d
        docker exec $(docker ps -q --filter name=latex) sh -c "cd /home/src && lualatex test"
        docker cp $(docker ps -q --filter name=latex):/home/src/test.pdf ./output/test.pdf
    
    - name: Upload release asset
      uses: softprops/action-gh-release@v2.0.2
      with:
        files: |
          ./output/test.pdf
        tag_name:
          ${{ steps.set_tag.outputs.TAG_NAME }}
        name:
          ${{ steps.set_release_name.outputs.RELEASE_NAME }}
        body:
          ${{ steps.set_body.outputs.BODY }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
